### ISSUE TITLE
[brtGTFS] Criar tabela `br_rj_riodejaneiro_gtfs_brt.realized_trips` 

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#12]
- criar sensor que lê o `raw_realized_trips` pelo drive
- chamar função do pacore rgtfs para tranformar em `realized_trips`
- subir table no BQ

**Comment by gabriel-milan** [comment]
movido para https://github.com/RJ-SMTR/maestro/issues/77
