### ISSUE TITLE
[capturas] Erros do SIGMOB deveriam ir para o canal `dagster-critical`

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#127]

**Comment by gabriel-milan** [comment]
- Fazer a chamada da função em https://github.com/RJ-SMTR/maestro/blob/main/repositories/helpers/hooks.py#L16 com a mensagem desejada em parâmetro

**Comment by JoaoCarabetta** [comment]
https://github.com/RJ-SMTR/maestro/blob/f50784f306eeb6caedbb97097582a3911b85c789/repositories/capturas/br_rj_riodejaneiro_sigmob/data.py#L21
