### ISSUE TITLE
[GTFS] colocar uma versão no BigQuery

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#13]
Adicionar com partições corretas
partição: 
- gtfs_version_date

Com todas as colunas previstas na documentação: http://gtfs.org/

Tabelas:
- agency
- routes
- trips
- frequencies
- stops
- stop_times
- shapes
- calendar

dateset_id:
`br_rj_riodejaneiro_planned_gtfs`

**Comment by JoaoCarabetta** [comment]
Trocar para  `br_rj_riodejaneiro_gtfs_planned`

**Comment by gabriel-milan** [comment]
movido para #78
