### ISSUE TITLE
[mat-views] BUG: lançar materialização em runs separadas

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#135]

**Comment by gabriel-milan** [comment]
### Motivação

Em um dado momento, durante os testes de desenvolvimento de pipelines, foi constatado um evento onde as materializações para duas tabelas diferentes e sem relação de dependência foram lançadas em duas runs separadas. Apesar de não ser um problema, visto que elas não tinham dependência entre si, é algo a se investigar

**Comment by gabriel-milan** [comment]
Temos que aguardar #138 #126 e ver se o problema persiste e é replicável.
