### ISSUE TITLE
[gpsGTFS] criar funções no pacote rGTFS para gerar o gpsGTFS e subir no dagster

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#19]
- `generate_rgtfs_from_gps(planned_gtfs, gps)`
    |- `generate_rgtfs_from_realized_trips(planned_gtfs, realized_trips)`
    |- `generate_realized_trips_from_gps(planned_gtfs, gps)`

**Comment by gabriel-milan** [comment]
movido para #81
