### ISSUE TITLE
[qrcode] Fazer schedule para atualização dos dados via SIGMOB

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#82]
## Contexto

Informações de linhas e paradas associadas no app do QRCode são registradas hoej de forma manual. Idealmente, essas informações devem ser atualizadas conforme o SIGMOB.

## Dados

Fonte: https://rj-smtr.github.io/sigmob-api-docs/
- trips -> `trip_short_name`
- stop_times -> `trip_id`, `stop_id`

**Comment by fernandascovino** [comment]
duplicado de https://github.com/RJ-SMTR/mobilidade-rio-api/issues/33
